package coursescheduleapp.view;

import coursescheduleapp.model.CourseCollectionDB;
import coursescheduleapp.model.CoursePref;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoursePrefView.java
 *
 * Created on Apr 6, 2010, 7:13:48 PM
 */

/**
 *
 * @author Drew
 */
public class CoursePrefView extends javax.swing.JPanel {

	private CoursePref coursePref;
	private int numEquiv, numSelect;
	private CourseCollectionDB courseDB;
    /** Creates new form CoursePrefView */
    public CoursePrefView() {
        initComponents();
        
    }
    
    public void setCoursePref(CoursePref coursePref, int numEquiv, int numSelect, CourseCollectionDB courseDB )
    {
    	this.coursePref = coursePref;
    	this.numEquiv = numEquiv;
    	this.numSelect = numSelect;
    	this.courseDB = courseDB;
    	
    	equivCourseSelectView1.setEquiv(coursePref.getEquivCourses(0), 0, courseDB);
        equivCourseSelectView2.setEquiv(coursePref.getEquivCourses(1), 1, courseDB);
        equivCourseSelectView3.setEquiv(coursePref.getEquivCourses(2), 2, courseDB);
        equivCourseSelectView4.setEquiv(coursePref.getEquivCourses(3), 3, courseDB);
        equivCourseSelectView5.setEquiv(coursePref.getEquivCourses(4), 4, courseDB);
        equivCourseSelectView6.setEquiv(coursePref.getEquivCourses(5), 5, courseDB);
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equivCourseSelectView1 = new EquivCourseSelectView();
        equivCourseSelectView2 = new EquivCourseSelectView();
        equivCourseSelectView3 = new EquivCourseSelectView();
        equivCourseSelectView4 = new EquivCourseSelectView();
        equivCourseSelectView5 = new EquivCourseSelectView();
        equivCourseSelectView6 = new EquivCourseSelectView();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(equivCourseSelectView1);
        add(equivCourseSelectView2);
        add(equivCourseSelectView3);
        add(equivCourseSelectView4);
        add(equivCourseSelectView5);
        add(equivCourseSelectView6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private EquivCourseSelectView equivCourseSelectView1;
    private EquivCourseSelectView equivCourseSelectView2;
    private EquivCourseSelectView equivCourseSelectView3;
    private EquivCourseSelectView equivCourseSelectView4;
    private EquivCourseSelectView equivCourseSelectView5;
    private EquivCourseSelectView equivCourseSelectView6;
    // End of variables declaration//GEN-END:variables

}
