package coursescheduleapp.view;

import java.sql.SQLException;

import coursescheduleapp.model.CourseCollectionDB;
import coursescheduleapp.model.CourseSelection;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CourseChoiceLB.java
 *
 * Created on Apr 6, 2010, 7:15:32 PM
 */

/**
 *
 * @author Drew
 */
public class CourseChoiceLB extends javax.swing.JPanel {

	
	private CourseSelection courseSelect;
	private int whichCourse, whichEquiv;

	private CourseCollectionDB courseDB;
	
    /** Creates new form CourseChoiceLB */
    public CourseChoiceLB() {
        initComponents();
    }
    
    public void setCoursePref(CourseSelection courseSelect, int whichCourse, int whichEquiv, CourseCollectionDB courseDB) throws SQLException
    {
    	this.courseSelect = courseSelect;
    	this.whichCourse = whichCourse;
    	this.whichEquiv = whichEquiv;
    	this.courseDB = courseDB;
    	
    	setChoiceLb();
    	
    	courseSelectView1.setCoursePref(courseSelect, whichCourse, whichEquiv, courseDB);
    }
    
    public void setChoiceLb()
    {
    	if (whichEquiv == 0)
    	{
    		choiceLB.setText("Choice " + (whichCourse + 1));
    	}
    	else
    	{
    		choiceLB.setText("        ");
    	}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceLB = new javax.swing.JLabel();
        courseSelectView1 = new CourseSelectView();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        choiceLB.setText("Choice");
        add(choiceLB);
        add(courseSelectView1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choiceLB;
    private CourseSelectView courseSelectView1;
    // End of variables declaration//GEN-END:variables

}
