package coursescheduleapp.view;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import coursescheduleapp.model.DayPref;
import coursescheduleapp.model.DayPrefs;
import coursescheduleapp.model.SchedulePref;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DayPrefView.java
 *
 * Created on Apr 6, 2010, 7:35:20 PM
 */


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author Drew
 */
public class DayPrefView extends javax.swing.JPanel implements ListSelectionListener{

	/** Creates new form DayPrefView */
	public DayPrefView() {
		model = new javax.swing.DefaultListModel();
		initComponents();
	}

	private SchedulePref schedPref;
	private javax.swing.DefaultListModel model;
	private DayPrefs dayPref;

	public void setSchedPref(SchedulePref schedPref)
	{
		this.schedPref = schedPref;
		
		model.addElement(DayPref.MON.toString());
		model.addElement(DayPref.TUES.toString());
		model.addElement(DayPref.WED.toString());
		model.addElement(DayPref.THUR.toString());
		model.addElement(DayPref.FRI.toString());
		model.addElement(DayPref.SAT.toString());
		
		//ArrayList<String> days = new ArrayList<String>();
		//schedPref.setPref(DayPref.DayPref.toString(), new DayPrefs());
		dayPref = new DayPrefs();
		schedPref.setPref(DayPref.DayPref.toString(), dayPref);
		
		

	}

	public void resetPref()
	{
		jList1.setModel(model);
		//ArrayList<String> days = new ArrayList<String>();
		
		//schedPref.setPref(DayPref.DayPref.toString(), new DayPrefs());
		dayPref.setDayPrefs(new ArrayList<String>());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		DayPrefLS = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();

		FormLayout thisLayout = new FormLayout(
				"max(p;5dlu), max(p;5dlu), max(p;5dlu), max(p;5dlu)", 
				"max(p;5dlu), max(p;5dlu), max(p;5dlu), max(p;5dlu)");
		this.setLayout(thisLayout);
		this.setPreferredSize(new java.awt.Dimension(266, 150));

		jLabel1.setText("Choose Preferred Days:");
		this.add(jLabel1, new CellConstraints("2, 1, 1, 1, default, default"));

		jList1.setModel(model);
		jList1.addListSelectionListener(this);
		jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
		jList1.setVisibleRowCount(3);
		DayPrefLS.setViewportView(jList1);

		this.add(DayPrefLS, new CellConstraints("2, 3, 1, 1, default, default"));
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane DayPrefLS;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList jList1;
	// End of variables declaration//GEN-END:variables

	@Override
	public void valueChanged(ListSelectionEvent e) {
		// TODO Auto-generated method stub
		if (e.getValueIsAdjusting() == false) {

			Object[] daysArr =  jList1.getSelectedValues();
			ArrayList<String> days = new ArrayList<String>();
			for (int i =0; i < daysArr.length; i++)
			{
				days.add((String)daysArr[i]);
			}
			
			schedPref.setPref(DayPref.DayPref.toString(), new DayPrefs(days));
			
			//need to set the DayPrefs object with the days arraylist
			dayPref.setDayPrefs(days);
			
			
		}

	}

}
