package coursescheduleapp.view;

import coursescheduleapp.model.CourseCollectionDB;
import coursescheduleapp.model.EquivCourseSelection;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EquivCourseSelectView.java
 *
 * Created on Apr 6, 2010, 7:14:26 PM
 */

/**
 *
 * @author Drew
 */
public class EquivCourseSelectView extends javax.swing.JPanel {

	private EquivCourseSelection equivSelect;
	private int whichEquiv;
	private CourseCollectionDB courseDB;
    /** Creates new form EquivCourseSelectView */
    public EquivCourseSelectView() {
        initComponents();
        
    }
    
   public void setEquiv(EquivCourseSelection equivSelect, int whichEquiv, CourseCollectionDB courseDB)
   {
	   this.equivSelect = equivSelect;
	   this.whichEquiv = whichEquiv;
   	   this.courseDB = courseDB;
   	   
	   coursePrefLB1.setCoursePref(equivSelect.getCourseSelection(0), 0, whichEquiv, courseDB);
       coursePrefLB2.setCoursePref(equivSelect.getCourseSelection(1), 1, whichEquiv, courseDB);
       coursePrefLB3.setCoursePref(equivSelect.getCourseSelection(2), 2, whichEquiv, courseDB);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coursePrefLB1 = new CoursePrefLB();
        coursePrefLB2 = new CoursePrefLB();
        coursePrefLB3 = new CoursePrefLB();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
        add(coursePrefLB1);
        add(coursePrefLB2);
        add(coursePrefLB3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CoursePrefLB coursePrefLB1;
    private CoursePrefLB coursePrefLB2;
    private CoursePrefLB coursePrefLB3;
    // End of variables declaration//GEN-END:variables

}
