package coursescheduleapp.view;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import coursescheduleapp.model.SchedulePref;
import coursescheduleapp.model.TimePref;
import coursescheduleapp.model.TimePrefs;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreferedTimeView.java
 *
 * Created on Apr 6, 2010, 7:33:49 PM
 */




/**
 * This code was edited or generated using CloudGarden's Jigloo
 * SWT/Swing GUI Builder, which is free for non-commercial
 * use. If Jigloo is being used commercially (ie, by a corporation,
 * company or business for any purpose whatever) then you
 * should purchase a license for each developer using Jigloo.
 * Please visit www.cloudgarden.com for details.
 * Use of Jigloo implies acceptance of these licensing terms.
 * A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
 * THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
 * LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
 */
/**
 *
 * @author Drew
 */
public class PreferedTimeView extends javax.swing.JPanel implements ItemListener {

	/** Creates new form PreferedTimeView */
	public PreferedTimeView() {
		this.model = new javax.swing.DefaultComboBoxModel();
		initComponents();
	}
	private SchedulePref schedPref;
	private javax.swing.DefaultComboBoxModel model;
	private TimePrefs timePref;

	public void setSchedPref(SchedulePref schedPref)
	{
		this.schedPref = schedPref;
		model.addElement(TimePref.NOPREF.toString());
		model.addElement(TimePref.MORNING.toString());
		model.addElement(TimePref.AFTERNOON.toString());
		model.addElement(TimePref.EVENING.toString());

		timePref = new TimePrefs(TimePref.NOPREF.toString());
		schedPref.setPref(TimePref.NOPREF.toString(), timePref);
	}
	public void resetPref()
	{
		timePref.setTimePref(TimePref.NOPREF.toString());
		model.setSelectedItem(TimePref.NOPREF.toString());
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		FormLayout thisLayout = new FormLayout(
				"max(p;5dlu), max(p;5dlu), max(p;5dlu), max(p;5dlu)", 
		"max(p;5dlu), max(p;5dlu), max(p;5dlu), max(p;5dlu)");
		this.setLayout(thisLayout);

		{
			jLabel1 = new javax.swing.JLabel();
			this.add(jLabel1, new CellConstraints("2, 1, 1, 1, center, default"));
			jLabel1.setText("Choose Preferred Time:");
		}
		{
			timePrefCB = new javax.swing.JComboBox();
			this.add(timePrefCB, new CellConstraints("2, 3, 1, 1, fill, fill"));
			timePrefCB.setModel(model);
			timePrefCB.addItemListener(this);
		}

	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JComboBox timePrefCB;
	// End of variables declaration//GEN-END:variables
	@Override
	public void itemStateChanged(ItemEvent arg0) {
		// TODO Auto-generated method stub
		if (arg0.getStateChange()== ItemEvent.SELECTED)
		{
			if (timePref != null)
			{
				timePref.setTimePref((String)arg0.getItem());
			}
		}

	}

}
