package coursescheduleapp.view;

import coursescheduleapp.model.Model;
import java.awt.BorderLayout;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScheduleView.java
 *
 * Created on Apr 6, 2010, 7:14:00 PM
 */


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author Drew
 */
public class ScheduleView extends javax.swing.JPanel {

	
	private Model d;
    /** Creates new form ScheduleView */
    public ScheduleView() {
        initComponents();
    }

    public void setModel(Model d)
    {
    	this.d = d;
    	resultsView1.setModel(d);
    	submitPanel1.setModel(d);
    	
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitPanel1 = new submitPanel();
        resultsView1 = new ResultsView();

        setLayout(new java.awt.BorderLayout());
        add(submitPanel1, java.awt.BorderLayout.NORTH);
        this.add(resultsView1, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ResultsView resultsView1;
    private submitPanel submitPanel1;
    // End of variables declaration//GEN-END:variables
	public void save() {
		// TODO Auto-generated method stub
		resultsView1.save();
		
	}
	
	public void setView(SchedViewI view)
	{
		resultsView1.setView(view);
	}

	public void print() {
		// TODO Auto-generated method stub
		resultsView1.print();
	}

}
