package coursescheduleapp.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TreeMap;

import coursescheduleapp.model.LeastDayPref;
import coursescheduleapp.model.LeastHourPref;
import coursescheduleapp.model.Preference;
import coursescheduleapp.model.SchedulePref;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.LayoutStyle;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchedPrefView.java
 *
 * Created on Apr 6, 2010, 7:12:49 PM
 */


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author Drew
 */
public class SchedPrefView extends javax.swing.JPanel implements ActionListener{

	
    /** Creates new form SchedPrefView */
    public SchedPrefView() {
        initComponents();
    }
    private SchedulePref schedPref;
    public void setSchedPref(SchedulePref schedPref)
    {
    	this.schedPref = schedPref;
    	schedPref.setPref("hour", new LeastHourPref());
    	schedPref.setPref("day", new LeastDayPref());
    	
    	this.preferedTimeView1.setSchedPref(schedPref);
    	this.dayPrefView1.setSchedPref(schedPref);
    	this.timeSpacingPrefView1.setSchedPref(schedPref);
    	
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	GroupLayout thisLayout = new GroupLayout(this);
    	this.setLayout(thisLayout);
    	this.setPreferredSize(new java.awt.Dimension(176, 292));
        jLabel1 = new javax.swing.JLabel();
        preferedTimeView1 = new PreferedTimeView();
        dayPrefView1 = new DayPrefView();
        timeSpacingPrefView1 = new TimeSpacingPrefView();
        {
        	resetBt = new JButton();
        	resetBt.setText("Reset");
        	resetBt.setActionCommand("Reset");
            resetBt.addActionListener(this);
        }

        jLabel1.setText("Schedule Preferences");
        thisLayout.setVerticalGroup(thisLayout.createSequentialGroup()
        	.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 13, GroupLayout.PREFERRED_SIZE)
        	.addGap(30)
        	.addComponent(preferedTimeView1, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        	.addGap(0, 25, Short.MAX_VALUE)
        	.addComponent(dayPrefView1, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        	.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
        	.addComponent(timeSpacingPrefView1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
        	.addGap(25)
        	.addComponent(resetBt, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE));
        thisLayout.setHorizontalGroup(thisLayout.createSequentialGroup()
        	.addContainerGap()
        	.addGroup(thisLayout.createParallelGroup()
        	    .addGroup(thisLayout.createSequentialGroup()
        	        .addComponent(preferedTimeView1, 0, 148, Short.MAX_VALUE)
        	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED))
        	    .addGroup(GroupLayout.Alignment.LEADING, thisLayout.createSequentialGroup()
        	        .addGap(0, 0, GroupLayout.PREFERRED_SIZE)
        	        .addComponent(dayPrefView1, 0, 148, Short.MAX_VALUE))
        	    .addGroup(thisLayout.createSequentialGroup()
        	        .addComponent(timeSpacingPrefView1, 0, 149, Short.MAX_VALUE)
        	        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED))
        	    .addGroup(GroupLayout.Alignment.LEADING, thisLayout.createSequentialGroup()
        	        .addComponent(resetBt, 0, 64, Short.MAX_VALUE)
        	        .addGap(85))
        	    .addGroup(GroupLayout.Alignment.LEADING, thisLayout.createSequentialGroup()
        	        .addPreferredGap(preferedTimeView1, jLabel1, LayoutStyle.ComponentPlacement.INDENT)
        	        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE, GroupLayout.PREFERRED_SIZE)
        	        .addGap(33)))
        	.addContainerGap());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DayPrefView dayPrefView1;
    private javax.swing.JLabel jLabel1;
    private PreferedTimeView preferedTimeView1;
    private JButton resetBt;
    private TimeSpacingPrefView timeSpacingPrefView1;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent arg0) {
		// TODO Auto-generated method stub
		if ("Reset".equals(arg0.getActionCommand()))
		{
			schedPref.setPref(new TreeMap<String,Preference>());
			schedPref.setPref("hour", new LeastHourPref());
	    	schedPref.setPref("day", new LeastDayPref());
			dayPrefView1.resetPref();
			preferedTimeView1.resetPref();
			timeSpacingPrefView1.resetPref();
		}
	}

}
