package coursescheduleapp.view;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import coursescheduleapp.model.CourseSpacing;
import coursescheduleapp.model.SchedulePref;
import coursescheduleapp.model.TimeSpacingPrefs;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TimeSpacingPrefView.java
 *
 * Created on Apr 6, 2010, 7:41:27 PM
 */


/**
* This code was edited or generated using CloudGarden's Jigloo
* SWT/Swing GUI Builder, which is free for non-commercial
* use. If Jigloo is being used commercially (ie, by a corporation,
* company or business for any purpose whatever) then you
* should purchase a license for each developer using Jigloo.
* Please visit www.cloudgarden.com for details.
* Use of Jigloo implies acceptance of these licensing terms.
* A COMMERCIAL LICENSE HAS NOT BEEN PURCHASED FOR
* THIS MACHINE, SO JIGLOO OR THIS CODE CANNOT BE USED
* LEGALLY FOR ANY CORPORATE OR COMMERCIAL PURPOSE.
*/
/**
 *
 * @author Drew
 */
public class TimeSpacingPrefView extends javax.swing.JPanel implements ItemListener{

    /** Creates new form TimeSpacingPrefView */
    public TimeSpacingPrefView() {
    	model = new javax.swing.DefaultComboBoxModel();
        initComponents();
    }
    private SchedulePref schedPref;
    private javax.swing.DefaultComboBoxModel model;
    private TimeSpacingPrefs spacing;
    public void setSchedPref(SchedulePref schedPref)
    {
    	this.schedPref = schedPref;
    	model.addElement(CourseSpacing.NOPREF.toString());
    	model.addElement(CourseSpacing.TENMIN.toString());
    	model.addElement(CourseSpacing.HOUR.toString());
    	
    	spacing = new TimeSpacingPrefs();
    	schedPref.setPref(CourseSpacing.CourseSpacing.toString(), spacing);
    	
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        FormLayout thisLayout = new FormLayout(
        		"max(p;5dlu), max(p;5dlu), max(p;5dlu), max(p;5dlu)", 
        		"max(p;5dlu), 18dlu, 5dlu, max(p;5dlu)");
        this.setLayout(thisLayout);

        jLabel1.setText("Choose time spacing:   ");
        this.add(jLabel1, new CellConstraints("2, 1, 1, 1, fill, top"));

        jComboBox1.setModel(model);
        this.add(jComboBox1, new CellConstraints("2, 2, 1, 1, fill, fill"));
        jComboBox1.addItemListener(this);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
	public void itemStateChanged(ItemEvent arg0) {
		// TODO Auto-generated method stub
		if (arg0.getStateChange()== ItemEvent.SELECTED)
		{
			System.out.println(arg0.getItem());
			//schedPref.setPref(CourseSpacing.CourseSpacing.toString(), arg0.getItem());
			if (spacing != null)
			{
			spacing.setSpacing((String)arg0.getItem());
			}
		}
		
	}
	public void resetPref() {
		// TODO Auto-generated method stub
		spacing.setSpacing(CourseSpacing.NOPREF.toString());
    	model.setSelectedItem(CourseSpacing.NOPREF.toString());
		
	}
}
